// Generated from carolcalicchioart.com store data (Sept 2026). Edit freely.
export type Collection = "blue" | "white" | "recent" | "minis" | "surfboards" | "books";
export type Work = {
  slug: string; file: string; name: string; price: number; sold: boolean; available: boolean;
  medium: string | null; width: number | null; height: number | null; iw: number; ih: number; color: string;
  collections: Collection[]; description: string; kind: "painting" | "surfboard" | "book" | "mini";
};

export const works: Work[] = [
 {
  "slug": "alluring-light",
  "file": "alluring-light",
  "name": "Alluring Light",
  "price": 14000,
  "sold": false,
  "available": true,
  "medium": "Acrylic On Canvas & Mixed Media",
  "width": 48,
  "height": 36,
  "iw": 1201,
  "ih": 1600,
  "color": "#a2696b",
  "collections": [],
  "description": "48 x 36 in. Acrylic On Canvas & Mixed Media",
  "kind": "painting"
 },
 {
  "slug": "aphrodite-s-love",
  "file": "aphrodite-s-love",
  "name": "Aphrodite's Love",
  "price": 6500,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas & Mixed Media",
  "width": 36,
  "height": 36,
  "iw": 1582,
  "ih": 1600,
  "color": "#b98ca0",
  "collections": [],
  "description": "36 x 36 in. Acrylic on Canvas & Mixed Media",
  "kind": "painting"
 },
 {
  "slug": "aphrodite-s-playground",
  "file": "aphrodite-s-playground",
  "name": "Aphrodite's Playground",
  "price": 10000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 516,
  "ih": 633,
  "color": "#e1d9e0",
  "collections": [
   "white"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "aphrodite",
  "file": "aphrodite",
  "name": "Aphrodite",
  "price": 900,
  "sold": false,
  "available": true,
  "medium": null,
  "width": 14,
  "height": 14,
  "iw": 1127,
  "ih": 1100,
  "color": "#a5a29d",
  "collections": [
   "minis"
  ],
  "description": "\"Goddess Collection\" 14 x 14 in.",
  "kind": "mini"
 },
 {
  "slug": "athena",
  "file": "athena",
  "name": "Athena",
  "price": 900,
  "sold": false,
  "available": true,
  "medium": null,
  "width": 14,
  "height": 14,
  "iw": 1128,
  "ih": 1143,
  "color": "#a5a097",
  "collections": [
   "minis"
  ],
  "description": "\"Goddess Collection\" 14 x 14 in.",
  "kind": "mini"
 },
 {
  "slug": "auspicious-dream",
  "file": "auspicious-dream",
  "name": "Auspicious Dream",
  "price": 10000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 521,
  "ih": 640,
  "color": "#9194b5",
  "collections": [
   "recent"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "awakened-love",
  "file": "awakened-love",
  "name": "Awakened Love",
  "price": 12000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 266,
  "ih": 339,
  "color": "#b17e84",
  "collections": [],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "barbadian-night",
  "file": "barbadian-night",
  "name": "Barbadian Night",
  "price": 16000,
  "sold": false,
  "available": true,
  "medium": "Oil on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1070,
  "ih": 1056,
  "color": "#6d718e",
  "collections": [],
  "description": "48 x 48 in. Oil on Canvas",
  "kind": "painting"
 },
 {
  "slug": "beauty-of-darkness",
  "file": "beauty-of-darkness",
  "name": "Beauty of Darkness",
  "price": 9000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1569,
  "ih": 1600,
  "color": "#757579",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "beyond-the-ozone",
  "file": "beyond-the-ozone",
  "name": "Beyond the Ozone",
  "price": 16000,
  "sold": true,
  "available": false,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 72,
  "iw": 1444,
  "ih": 1166,
  "color": "#c38d8b",
  "collections": [],
  "description": "60 x 72 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "beyond-your-wildest-dreams",
  "file": "beyond-your-wildest-dreams",
  "name": "Beyond Your Wildest Dreams",
  "price": 7000,
  "sold": false,
  "available": true,
  "medium": "Acrylic Paint, Healing Stones on Glass Framed",
  "width": 30,
  "height": 55,
  "iw": 1600,
  "ih": 881,
  "color": "#b26a96",
  "collections": [],
  "description": "30 x 55 in. Acrylic Paint, Healing Stones on Glass Framed",
  "kind": "painting"
 },
 {
  "slug": "bright-day",
  "file": "bright-day",
  "name": "Bright Day",
  "price": 3500,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 36,
  "height": 24,
  "iw": 1057,
  "ih": 1600,
  "color": "#a87b7d",
  "collections": [],
  "description": "36 x 24 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "captain-s-dream",
  "file": "captain-s-dream",
  "name": "Captain's Dream",
  "price": 16000,
  "sold": true,
  "available": false,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 1276,
  "ih": 1600,
  "color": "#556880",
  "collections": [
   "recent"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "catalonian-flowerbed",
  "file": "catalonian-flowerbed",
  "name": "Catalonian Flowerbed",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 772,
  "ih": 772,
  "color": "#ad7367",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "celestial-moonlight",
  "file": "celestial-moonlight",
  "name": "Celestial Moonlight",
  "price": 18000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 1285,
  "ih": 1600,
  "color": "#506d90",
  "collections": [
   "recent"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "celestial-seasons",
  "file": "celestial-seasons",
  "name": "Celestial Seasons",
  "price": 20000,
  "sold": true,
  "available": false,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1590,
  "ih": 1600,
  "color": "#637479",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "cerulean-turquoise",
  "file": "cerulean-turquoise",
  "name": "Cerulean Turquoise",
  "price": 9000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 441,
  "ih": 436,
  "color": "#678698",
  "collections": [
   "blue"
  ],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "circadian-splendor",
  "file": "circadian-splendor",
  "name": "Circadian Splendor",
  "price": 12000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas Framed",
  "width": 48,
  "height": 60,
  "iw": 1600,
  "ih": 1293,
  "color": "#c7b6ae",
  "collections": [
   "white"
  ],
  "description": "48 x 60 in. Acrylic on Canvas Framed",
  "kind": "painting"
 },
 {
  "slug": "crystal",
  "file": "crystal",
  "name": "Crystal",
  "price": 14000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 799,
  "ih": 1012,
  "color": "#2d99c6",
  "collections": [
   "blue"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "day-dreamers-in-paradise",
  "file": "day-dreamers-in-paradise",
  "name": "Day Dreamers in Paradise",
  "price": 9000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 390,
  "ih": 502,
  "color": "#a87375",
  "collections": [
   "recent"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "deep-marine-swirl",
  "file": "deep-marine-swirl",
  "name": "Deep Marine Swirl",
  "price": 9000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 433,
  "ih": 432,
  "color": "#5f7c86",
  "collections": [
   "blue"
  ],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "diana",
  "file": "diana",
  "name": "Diana",
  "price": 900,
  "sold": false,
  "available": true,
  "medium": null,
  "width": 14,
  "height": 14,
  "iw": 1148,
  "ih": 1124,
  "color": "#a7a5a0",
  "collections": [
   "minis"
  ],
  "description": "\"Goddess Collection\" 14 x 14 in.",
  "kind": "mini"
 },
 {
  "slug": "etruscan-horse",
  "file": "etruscan-horse",
  "name": "Etruscan Horse",
  "price": 10000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 1150,
  "ih": 1454,
  "color": "#7d7279",
  "collections": [
   "recent"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "everything-i-left-behind",
  "file": "everything-i-left-behind",
  "name": "Everything I Left Behind",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic Paint, Healing Stones on Glass",
  "width": 37,
  "height": 51,
  "iw": 1600,
  "ih": 1158,
  "color": "#7c89ad",
  "collections": [],
  "description": "37 x 51 in. Acrylic Paint, Healing Stones on Glass",
  "kind": "painting"
 },
 {
  "slug": "far-away-places",
  "file": "far-away-places",
  "name": "Far Away Places",
  "price": 15000,
  "sold": true,
  "available": false,
  "medium": "Acrylic on Canvas",
  "width": 36,
  "height": 48,
  "iw": 1426,
  "ih": 1038,
  "color": "#807774",
  "collections": [],
  "description": "36 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "flora-paradiso",
  "file": "flora-paradiso",
  "name": "Flora Paradiso",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 449,
  "ih": 420,
  "color": "#ab8a8d",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "flower-power-coffee-table-book",
  "file": "flower-power-coffee-table-book",
  "name": "Flower Power Coffee Table Book",
  "price": 65,
  "sold": false,
  "available": false,
  "medium": null,
  "width": null,
  "height": null,
  "iw": 1500,
  "ih": 1523,
  "color": "#807d87",
  "collections": [
   "books"
  ],
  "description": "",
  "kind": "book"
 },
 {
  "slug": "forever",
  "file": "forever",
  "name": "Forever",
  "price": 16000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas Can be hung Horizontally or Vertically",
  "width": 60,
  "height": 72,
  "iw": 1450,
  "ih": 1180,
  "color": "#a47b70",
  "collections": [],
  "description": "60 x 72 in. Acrylic on Canvas Can be hung Horizontally or Vertically",
  "kind": "painting"
 },
 {
  "slug": "fruit-life-still",
  "file": "fruit-life-still",
  "name": "Fruit Life Still",
  "price": 6000,
  "sold": false,
  "available": true,
  "medium": "Oil on Canvas",
  "width": 20,
  "height": 20,
  "iw": 544,
  "ih": 447,
  "color": "#90705a",
  "collections": [],
  "description": "Dimensions: 20x20 in. Oil on Canvas",
  "kind": "painting"
 },
 {
  "slug": "gaia",
  "file": "gaia",
  "name": "Gaia",
  "price": 900,
  "sold": false,
  "available": true,
  "medium": null,
  "width": 14,
  "height": 14,
  "iw": 1105,
  "ih": 1113,
  "color": "#a79f95",
  "collections": [
   "minis"
  ],
  "description": "\"Goddess Collection\" 14 x 14 in.",
  "kind": "mini"
 },
 {
  "slug": "galaxy-of-love",
  "file": "galaxy-of-love",
  "name": "Galaxy of Love",
  "price": 16000,
  "sold": false,
  "available": true,
  "medium": "Oil on Canvas",
  "width": 48,
  "height": 48,
  "iw": 499,
  "ih": 486,
  "color": "#947f96",
  "collections": [],
  "description": "48 x 48 in. Oil on Canvas",
  "kind": "painting"
 },
 {
  "slug": "garden-of-white",
  "file": "garden-of-white",
  "name": "Garden of White",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 671,
  "ih": 674,
  "color": "#e6e1e7",
  "collections": [
   "white"
  ],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "gardenia-awakening",
  "file": "gardenia-awakening",
  "name": "Gardenia Awakening",
  "price": 8500,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 36,
  "iw": 1196,
  "ih": 1600,
  "color": "#d3ccce",
  "collections": [
   "white"
  ],
  "description": "48 x 36 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "gardenia-goddess",
  "file": "gardenia-goddess",
  "name": "Gardenia Goddess",
  "price": 8500,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 36,
  "iw": 1209,
  "ih": 1600,
  "color": "#cec6cb",
  "collections": [
   "white"
  ],
  "description": "48 x 36 Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "golden-gardenia",
  "file": "golden-gardenia",
  "name": "Golden Gardenia",
  "price": 900,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 14,
  "height": 14,
  "iw": 1106,
  "ih": 1120,
  "color": "#5f6566",
  "collections": [
   "minis"
  ],
  "description": "14 x 14 in. Acrylic on Canvas",
  "kind": "mini"
 },
 {
  "slug": "golden-hibiscus",
  "file": "golden-hibiscus",
  "name": "Golden Hibiscus",
  "price": 900,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 14,
  "height": 14,
  "iw": 1035,
  "ih": 1049,
  "color": "#757262",
  "collections": [
   "minis"
  ],
  "description": "14 x 14 in. Acrylic on Canvas",
  "kind": "mini"
 },
 {
  "slug": "homage-to-lilly",
  "file": "homage-to-lilly",
  "name": "Homage to Lilly",
  "price": 3500,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1456,
  "ih": 1464,
  "color": "#7fa595",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "hummingbird-bliss",
  "file": "hummingbird-bliss",
  "name": "Hummingbird Bliss",
  "price": 6000,
  "sold": true,
  "available": false,
  "medium": "Oil on Canvas",
  "width": 36,
  "height": 36,
  "iw": 1558,
  "ih": 1564,
  "color": "#828d84",
  "collections": [],
  "description": "36 x 36 in. Oil on Canvas",
  "kind": "painting"
 },
 {
  "slug": "hummingbirds",
  "file": "hummingbirds",
  "name": "Hummingbirds",
  "price": 18000,
  "sold": false,
  "available": true,
  "medium": "Oil on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1558,
  "ih": 1600,
  "color": "#a38263",
  "collections": [],
  "description": "48 x 48 in. Oil on Canvas",
  "kind": "painting"
 },
 {
  "slug": "lavender-garden",
  "file": "lavender-garden",
  "name": "Lavender Garden",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 489,
  "ih": 631,
  "color": "#b3aba1",
  "collections": [],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "light-captured-energy",
  "file": "light-captured-energy",
  "name": "Light Captured Energy",
  "price": 7500,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 40,
  "height": 30,
  "iw": 1122,
  "ih": 1500,
  "color": "#0e5b97",
  "collections": [
   "blue"
  ],
  "description": "40 x 30 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "mercurial-mondays",
  "file": "mercurial-mondays",
  "name": "Mercurial Mondays",
  "price": 10000,
  "sold": false,
  "available": true,
  "medium": "Arylic & Mixed Media on Canvas",
  "width": 60,
  "height": 48,
  "iw": 1208,
  "ih": 1450,
  "color": "#957a8d",
  "collections": [
   "recent"
  ],
  "description": "60 x 48 in. Arylic & Mixed Media on Canvas",
  "kind": "painting"
 },
 {
  "slug": "midnight-bliss",
  "file": "midnight-bliss",
  "name": "Midnight Bliss",
  "price": 16000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas & Mixed Media",
  "width": 72,
  "height": 60,
  "iw": 1342,
  "ih": 1600,
  "color": "#8c8f99",
  "collections": [
   "recent"
  ],
  "description": "72 x 60 Acrylic on Canvas & Mixed Media",
  "kind": "painting"
 },
 {
  "slug": "morning-glory",
  "file": "morning-glory",
  "name": "Morning Glory",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 640,
  "ih": 596,
  "color": "#be7696",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "morning-white",
  "file": "morning-white",
  "name": "Morning White",
  "price": 6000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1579,
  "ih": 1600,
  "color": "#cab9b2",
  "collections": [
   "white"
  ],
  "description": "48 x 48 Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "ocean-power-coffee-table-book",
  "file": "ocean-power-coffee-table-book",
  "name": "Ocean Power Coffee Table Book",
  "price": 65,
  "sold": false,
  "available": false,
  "medium": null,
  "width": null,
  "height": null,
  "iw": 1600,
  "ih": 1599,
  "color": "#377fc4",
  "collections": [
   "books"
  ],
  "description": "",
  "kind": "book"
 },
 {
  "slug": "oleander-way",
  "file": "oleander-way",
  "name": "Oleander Way",
  "price": 4000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 24,
  "height": 30,
  "iw": 1564,
  "ih": 1176,
  "color": "#a73c40",
  "collections": [],
  "description": "24 x 30 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "opis-lepidoptera",
  "file": "opis-lepidoptera",
  "name": "Opus Lepidoptera",
  "price": 11000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1593,
  "ih": 1600,
  "color": "#9e6553",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "palm-beach-blooms",
  "file": "palm-beach-blooms",
  "name": "Palm Beach Blooms",
  "price": 10000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 960,
  "ih": 1162,
  "color": "#b95769",
  "collections": [
   "recent"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "palm-way",
  "file": "palm-way",
  "name": "Palm Way",
  "price": 10000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 1282,
  "ih": 1600,
  "color": "#9d9999",
  "collections": [
   "white"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "paradiso-grand-surfboard",
  "file": "paradiso-grand-surfboard",
  "name": "Paradiso Grand Surfboard",
  "price": 4000,
  "sold": true,
  "available": false,
  "medium": "NOMAD Surfboard made from \"Paradiso Grand\" Painting",
  "width": 20,
  "height": 72,
  "iw": 753,
  "ih": 1600,
  "color": "#cecad5",
  "collections": [
   "surfboards"
  ],
  "description": "NOMAD Surfboard made from \"Paradiso Grand\" Painting",
  "kind": "surfboard"
 },
 {
  "slug": "healing-water",
  "file": "pthalo-blue-light-refractions",
  "name": "Healing Water",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 36,
  "iw": 1201,
  "ih": 1600,
  "color": "#3baed8",
  "collections": [
   "blue"
  ],
  "description": "48 x 36 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "remember-me",
  "file": "remember-me",
  "name": "Remember Me",
  "price": 7000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas & Mixed Media",
  "width": 48,
  "height": 48,
  "iw": 1410,
  "ih": 1448,
  "color": "#c0b8a9",
  "collections": [
   "white"
  ],
  "description": "48 x 48 in. Acrylic on Canvas & Mixed Media",
  "kind": "painting"
 },
 {
  "slug": "rose-of-gold",
  "file": "rose-of-gold",
  "name": "Rose of Gold",
  "price": 900,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 14,
  "height": 14,
  "iw": 945,
  "ih": 979,
  "color": "#6d6d62",
  "collections": [
   "minis"
  ],
  "description": "14 x 14 in. Acrylic on Canvas",
  "kind": "mini"
 },
 {
  "slug": "sintra-magic",
  "file": "sintra-magic",
  "name": "Sintra Magic",
  "price": 11000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 241,
  "ih": 303,
  "color": "#ac717d",
  "collections": [],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "southern-cross",
  "file": "southern-cross",
  "name": "Southern Cross",
  "price": 14000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 60,
  "height": 48,
  "iw": 800,
  "ih": 1000,
  "color": "#2598cc",
  "collections": [
   "blue"
  ],
  "description": "60 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "st-barts-bound",
  "file": "st-barts-bound",
  "name": "St. Barths Bound",
  "price": 6000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 24,
  "height": 36,
  "iw": 432,
  "ih": 305,
  "color": "#486c72",
  "collections": [],
  "description": "24 x 36 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "summer-blossom",
  "file": "summer-blossom",
  "name": "Summer Blossom",
  "price": 11500,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1600,
  "ih": 1594,
  "color": "#b3727a",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "summer-day",
  "file": "summer-day",
  "name": "Summer Day",
  "price": 11520,
  "sold": false,
  "available": false,
  "medium": null,
  "width": null,
  "height": null,
  "iw": 1556,
  "ih": 1250,
  "color": "#b67160",
  "collections": [],
  "description": "",
  "kind": "painting"
 },
 {
  "slug": "the-call",
  "file": "the-call",
  "name": "The Call",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1370,
  "ih": 1364,
  "color": "#b47e90",
  "collections": [],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "the-provider",
  "file": "the-provider",
  "name": "The Provider",
  "price": 16000,
  "sold": false,
  "available": true,
  "medium": "Oil on Belgian Linen",
  "width": 70,
  "height": 80,
  "iw": 1170,
  "ih": 1072,
  "color": "#a9938e",
  "collections": [],
  "description": "70 x 80 in. Oil on Belgian Linen",
  "kind": "painting"
 },
 {
  "slug": "the-ram",
  "file": "the-ram",
  "name": "The Ram",
  "price": 5000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 30,
  "iw": 1215,
  "ih": 1600,
  "color": "#93939a",
  "collections": [],
  "description": "48 x 30 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "tiger-conch",
  "file": "tiger-conch",
  "name": "Tiger Conch",
  "price": 5000,
  "sold": false,
  "available": true,
  "medium": "Oil on Canvas",
  "width": 24,
  "height": 18,
  "iw": 640,
  "ih": 625,
  "color": "#8e777a",
  "collections": [],
  "description": "Dimensions: 24x 18 in. Oil on Canvas",
  "kind": "painting"
 },
 {
  "slug": "tropical",
  "file": "tropical",
  "name": "Tropical",
  "price": 14000,
  "sold": false,
  "available": false,
  "medium": "Oil on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1579,
  "ih": 1600,
  "color": "#9b756b",
  "collections": [],
  "description": "Dimensions: 48x48 in. Oil on Canvas",
  "kind": "painting"
 },
 {
  "slug": "white-flower-farm",
  "file": "white-flower-farm",
  "name": "White Flower Farm",
  "price": 8000,
  "sold": false,
  "available": true,
  "medium": "Acrylic on Canvas",
  "width": 48,
  "height": 48,
  "iw": 1070,
  "ih": 1054,
  "color": "#c8c8ca",
  "collections": [
   "white"
  ],
  "description": "48 x 48 in. Acrylic on Canvas",
  "kind": "painting"
 },
 {
  "slug": "winter-peonies",
  "file": "winter-peonies",
  "name": "Winter Peonies",
  "price": 6000,
  "sold": false,
  "available": true,
  "medium": "Acrylic On Canvas",
  "width": 48,
  "height": 48,
  "iw": 1600,
  "ih": 1572,
  "color": "#aeadad",
  "collections": [
   "white"
  ],
  "description": "Dimensions: 48 x 48 in. Acrylic On Canvas",
  "kind": "painting"
 }
];
