// Sample inquiries and orders so Carol can see the office with life in it.
// Every id starts with "demo_" so they can be wiped in one go when the real
// traffic starts. Names, numbers and emails are invented.
import type { Inquiry, StudioOrder } from "./types";

const ago = (hours: number) => new Date(Date.now() - hours * 3600 * 1000).toISOString();

export const DEMO_INQUIRIES: Inquiry[] = [
  {
    id: "demo_inq_1",
    createdAt: ago(2),
    kind: "inquiry",
    subject: "New Artwork Inquiry · Celestial Moonlight",
    name: "Margaret Whitfield",
    email: "margaret.whitfield@example.com",
    phone: "561-555-0142",
    message: "We just finished the living room in Gulf Stream and this is the one. Is it still available, and could we see it in person this week?",
    fields: { Artwork: "Celestial Moonlight (48 × 60 in.) $18,000" },
    workSlug: "celestial-moonlight",
    status: "new",
    notes: null,
    handledAt: null,
  },
  {
    id: "demo_inq_2",
    createdAt: ago(5),
    kind: "commission",
    subject: "New Commission Request",
    name: "Daniel and Priya Rao",
    email: "rao.family@example.com",
    phone: "(305) 555-0188",
    message: "Above a 9 ft sofa, west light in the afternoon. We love the blues but want something warmer.",
    fields: { "Approximate size or wall": "60 x 48 in., above a 9 ft sofa", "Series or palette": "Something like Crystal, warmer", "Inspired by": "Crystal" },
    workSlug: "crystal",
    status: "new",
    notes: null,
    handledAt: null,
  },
  {
    id: "demo_inq_3",
    createdAt: ago(26),
    kind: "visit",
    subject: "New Studio Visit Request",
    name: "Ellen Marsh",
    email: "ellen@example.com",
    phone: "561-555-0107",
    message: "Interior designer, bringing a client Thursday if you are open.",
    fields: { "What are you looking for": "A large piece for a client's dining room" },
    workSlug: null,
    status: "new",
    notes: null,
    handledAt: null,
  },
  {
    id: "demo_inq_4",
    createdAt: ago(50),
    kind: "contact",
    subject: "New Website Lead",
    name: "Tom Haverford",
    email: "tom.h@example.com",
    phone: null,
    message: "Loved the surfboards at The Breakers. Do you still have any of the limited edition boards?",
    fields: {},
    workSlug: null,
    status: "handled",
    notes: "Called back, sending photos of the last two boards.",
    handledAt: ago(40),
  },
  {
    id: "demo_inq_5",
    createdAt: ago(70),
    kind: "newsletter",
    subject: "New Newsletter Signup",
    name: null,
    email: "grace.lin@example.com",
    phone: null,
    message: "Joined the mailing list.",
    fields: {},
    workSlug: null,
    status: "handled",
    notes: null,
    handledAt: ago(70),
  },
];

const base = (id: string, hoursAgo: number, o: Partial<StudioOrder>): StudioOrder => ({
  id,
  ref: "",
  createdAt: ago(hoursAgo),
  updatedAt: ago(hoursAgo),
  name: "",
  email: "",
  phone: "",
  address: "",
  city: "",
  state: "FL",
  zip: "",
  payment: "Credit or debit card",
  delivery: "Ship to me",
  message: "",
  items: [],
  subtotal: 0,
  status: "new",
  notes: null,
  paidAt: null,
  carrier: null,
  tracking: null,
  shippedAt: null,
  deliveredAt: null,
  refundedAt: null,
  refundAmount: null,
  refundNote: null,
  stripeSessionId: null,
  ...o,
});

export const DEMO_ORDERS: StudioOrder[] = [
  base("demo_ord_1", 3, {
    ref: "CC-7Q2K1F",
    name: "Susan Bellamy",
    email: "susan.bellamy@example.com",
    phone: "561-555-0199",
    address: "210 Ocean Boulevard, Apt 4B",
    city: "Manalapan",
    zip: "33462",
    payment: "Credit or debit card",
    delivery: "White-glove delivery and installation",
    message: "Please call before delivery, the building needs a certificate of insurance.",
    items: [
      { slug: "hummingbirds", name: "Hummingbirds", qty: 1, price: 9500, image: "/art-sm/hummingbirds.jpg", dims: "48 × 36 in." },
      { slug: "palm-way", name: "Palm Way", qty: 1, price: 7000, image: "/art-sm/palm-way.jpg", dims: "36 × 36 in." },
    ],
    subtotal: 16500,
  }),
  base("demo_ord_2", 4 * 24, {
    ref: "CC-3M8XQ2",
    name: "Robert and Anne Keller",
    email: "kellers@example.com",
    phone: "(203) 555-0133",
    address: "14 Harbor Lane",
    city: "Greenwich",
    state: "CT",
    zip: "06830",
    payment: "Wire or check",
    delivery: "Ship to me",
    message: "",
    items: [{ slug: "aphrodite-s-love", name: "Aphrodite's Love", qty: 1, price: 6500, image: "/art-sm/aphrodite-s-love.jpg", dims: "36 × 36 in." }],
    subtotal: 6500,
    status: "shipped",
    paidAt: ago(3 * 24),
    carrier: "FedEx",
    tracking: "778899001122",
    shippedAt: ago(24),
    notes: "Wire received Tuesday. Crated by Palm Beach Art Handlers.",
  }),
  base("demo_ord_3", 12 * 24, {
    ref: "CC-9K1DZ7",
    name: "Lucia Ferrante",
    email: "lucia.f@example.com",
    phone: "561-555-0170",
    address: "801 South Ocean Blvd",
    city: "Delray Beach",
    zip: "33483",
    payment: "PayPal",
    delivery: "Pick up at the studio",
    items: [{ slug: "athena", name: "Athena", qty: 1, price: 900, image: "/art-sm/athena.jpg", dims: "14 × 14 in." }],
    subtotal: 900,
    status: "delivered",
    paidAt: ago(11 * 24),
    carrier: "Picked up at the studio",
    shippedAt: ago(9 * 24),
    deliveredAt: ago(9 * 24),
  }),
];
